# This is a basic workflow to help you get started with Actions

name: Upload Angular Dashboard APP
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: 🔨 Build Project
        run: |
          cd ravn-challenge
          npm install --legacy-peer-deps
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.huellitasvetspa.com
          local-dir: /home/runner/work/ravn-fron-code-challenge/ravn-fron-code-challenge/ravn-challenge/dist/ravn-challenge/browser/
          username: ravn-user@ravn-challenge.pacasoft.cloud
          password: ${{ secrets.FTPPASSWORD }}
          protocol: ftps
          port: 21 # todo replace with your web host's ftps port
